version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.x
    commands:
      - yarn
  build:
    commands:
      - NODE_OPTIONS=--max-old-space-size=4096 yarn build-only

artifacts:
  files:
    - 'build/**/*'