version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.x
    commands:
      - yarn
  build:
    commands:
      - yarn build-only
artifacts:
  files:
    - 'dist/**/*'
cache:
  paths:
    - 'node_modules/**/*'
